name: dulcinea
favicon: null
layout_spectrum: 0.5729668135754764
typography_spectrum: 0.5882900396827608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9786160951480269
  lightness: 0.4492525104433298
  saturation: 0.23352271621115506
  rhythmicContrast: 0.4983616485260427
purpose: []
